;by jNizM  http://ahkscript.org/boards/viewtopic.php?p=24584#p24584

ComObjCreate("shell.application").ControlPanelItem("appwiz.cpl")      ; => Add/Remove Programs
;~ ComObjCreate("shell.application").ControlPanelItem("calc")            ; => Calculator
;~ ComObjCreate("shell.application").ControlPanelItem("control")         ; => Control Panel
;~ ComObjCreate("shell.application").ControlPanelItem("dcomcnfg")        ; => Component Services
;~ ComObjCreate("shell.application").ControlPanelItem("compmgmt.msc")    ; => Computer Management
;~ ComObjCreate("shell.application").ControlPanelItem("timedate.cpl")    ; => Date and Time Properties
;~ ComObjCreate("shell.application").ControlPanelItem("dfrgui")          ; => Defragment User Interface
;~ ComObjCreate("shell.application").ControlPanelItem("devmgmt.msc")     ; => Device Manager
;~ ComObjCreate("shell.application").ControlPanelItem("hdwwiz.cpl")      ; => Device Manager
;~ ComObjCreate("shell.application").ControlPanelItem("diskmgmt.msc")    ; => Disk Management
;~ ComObjCreate("shell.application").ControlPanelItem("eventvwr.msc")    ; => Event Viewer
;~ ComObjCreate("shell.application").ControlPanelItem("gpedit.msc")      ; => Group Policy Editor
;~ ComObjCreate("shell.application").ControlPanelItem("iexplore")        ; => Internet Explorer
;~ ComObjCreate("shell.application").ControlPanelItem("inetcpl.cpl")     ; => Internet Properties
;~ ComObjCreate("shell.application").ControlPanelItem("secpol.msc")      ; => Local Security Settings
;~ ComObjCreate("shell.application").ControlPanelItem("lusrmgr.msc")     ; => Local Users and Groups
;~ ComObjCreate("shell.application").ControlPanelItem("logoff")          ; => Logs You Out Of Windows
;~ ComObjCreate("shell.application").ControlPanelItem("main.cpl")        ; => Mouse Properties
;~ ComObjCreate("shell.application").ControlPanelItem("ncpa.cpl")        ; => Network Connections
;~ ComObjCreate("shell.application").ControlPanelItem("notepad")         ; => Notepad
;~ ComObjCreate("shell.application").ControlPanelItem("perfmon.msc")     ; => Performance Monitor
;~ ComObjCreate("shell.application").ControlPanelItem("powercfg.cpl")    ; => Power Configuration
;~ ComObjCreate("shell.application").ControlPanelItem("intl.cpl")        ; => Regional Settings
;~ ComObjCreate("shell.application").ControlPanelItem("mstsc")           ; => Remote Desktop
;~ ComObjCreate("shell.application").ControlPanelItem("wscui.cpl")       ; => Security Center
;~ ComObjCreate("shell.application").ControlPanelItem("services.msc")    ; => Services
;~ ComObjCreate("shell.application").ControlPanelItem("fsmgmt.msc")      ; => Shared Folders/MMC
;~ ComObjCreate("shell.application").ControlPanelItem("shutdown")        ; => Shuts Down Windows
;~ ComObjCreate("shell.application").ControlPanelItem("snippingtool")    ; => Snipping Tool
;~ ComObjCreate("shell.application").ControlPanelItem("sndvol")          ; => Sound Volume
;~ ComObjCreate("shell.application").ControlPanelItem("mmsys.cpl")       ; => Sounds and Audio
;~ ComObjCreate("shell.application").ControlPanelItem("StikyNot")        ; => Sticky Note
;~ ComObjCreate("shell.application").ControlPanelItem("msconfig")        ; => System Configuration Utility
;~ ComObjCreate("shell.application").ControlPanelItem("msinfo32")        ; => System Information
;~ ComObjCreate("shell.application").ControlPanelItem("sysdm.cpl")       ; => System Properties
;~ ComObjCreate("shell.application").ControlPanelItem("taskmgr")         ; => Task Manager
;~ ComObjCreate("shell.application").ControlPanelItem("netplwiz")        ; => User Accounts
;~ ComObjCreate("shell.application").ControlPanelItem("utilman")         ; => Utility Manager
;~ ComObjCreate("shell.application").ControlPanelItem("firewall.cpl")    ; => Windows Firewall
;~ ComObjCreate("shell.application").ControlPanelItem("wf.msc")          ; => Windows Firewall with Advanced Security
;~ ComObjCreate("shell.application").ControlPanelItem("wmimgmt.msc")     ; => Windows Management Infrastructure
;~ ComObjCreate("shell.application").ControlPanelItem("wuapp")           ; => Windows Update App Manager
;~ ComObjCreate("shell.application").ControlPanelItem("write")           ; => Wordpad
;~ ComObjCreate("shell.application").ShutdownWindows()   